# https://github.com/sympy/sympy/blob/master/.travis.yml
# https://github.com/codecov/example-python
# https://docs.travis-ci.com
# https://stackoverflow.com/a/3237883
# https://stackoverflow.com/a/5688592
# https://stackoverflow.com/a/6270803

language: python

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install pytest-cov codecov

install:
  - pip install .

script:
  # for testing, limit downloads from the resource servers to only the selected job for
  # PRs and the master branch; note that the master branch is tested weekly via `cron`,
  # so this ensures all Python versions will be periodically integration tested with the
  # resource servers
  - set -e
  - NUM_JOBS=4
  - SELECTED_JOB=$((10#$(date +%V) % $NUM_JOBS))  # identify a job based on week of the year
  - |
    if [[ $TRAVIS_PULL_REQUEST != "false" && $SELECTED_JOB == $JOB_ID ]]; then
      # download resources for selected job on a pull request
      export DOWNLOADS_ENABLED=true
    elif [[ $TRAVIS_BRANCH == "master" && $SELECTED_JOB == $JOB_ID ]]; then
      # download resources for selected job on master branch
      export DOWNLOADS_ENABLED=true
    fi
  - pytest --cov=snps tests
  - |
    if [[ $SELECTED_JOB == $JOB_ID ]]; then
      codecov
    fi

stages:
  - check formatting
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: check formatting
      python: 3.6
      before_install:
        - pip install black
      script:
        - black --check --diff .
    - stage: test
      python: 3.5
      env: JOB_ID=0
    - python: 3.6
      env: JOB_ID=1
    - python: 3.7
      env: JOB_ID=2
    - python: 3.8
      env: JOB_ID=3
    - stage: deploy
      python: 3.6
      script: skip
      deploy:
        - provider: pypi
          user: "apriha"
          password:
            secure: "UgERaEw1BVm/crJiCBuctaj79ofya/eCOwnRfpLlhpap57dlEHzlfaGGQNMlRxPWPkHWAy0wGuaYfG2ZHy1F5WaiZqwfPdsA8wISZflqoudZuvoKWaThByVYebcx8nGU6qCLbA3VxDAcnRyg7ncC2DJm0HKnfAYltDjTPujq6Ui8h/hobwvB5xZJktfSjOWZwrvZ1HIqBSpWuPg5eJjoQAifuMwgnfPh2lq+w+UFuLd5L12+uwWxIkKgcx8bsmVcpixddRv6broozVRxj1ctvJiq8/CzclsLgtAtthsTxLjadr9llCXTy3HnYy01M1LHUAiN8K/Qpu81k/JWdGmvBwJRIHXpJSZLrDM6VjfPtainZbBxOZaffFxqzdY4Tk3/1f4c11FCsVCcZJfV+phIFxZrNNhBOMO7+6wA17iGEHy5L6RdighZAv5JKKvAnZGnbYv+BO0x8DtTjqxN1BPI2tMNjQm8S8I/p5YKv0u1FWN8KwOyqYn2ccSLv6fuzRU89iUIvqiuhRA6xdmiouTUElfstjVuY7Nz68giZnhN4/iX6nRPU3Pgaiuy/ajOwJka5JN5gWFDFq3fmuoCixGB3q5t+FplN2t6yoTogoZX9DN1g0Ju4PSCnjJ7qL5juColkDkyUv8W1SInb/OAXTDSzxVSOcMBNxPiHNPzukx25rs="
          distributions: "sdist bdist_wheel"
          on:
            branch: master
            tags: true
